name: Python

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)" > "release_${{ matrix.python-version }}"

      - name: Save output artifact
        uses: actions/upload-artifact@v1
        with:
          name: "release_${{ matrix.python-version }}"
          path: "release_${{ matrix.python-version }}"
